http:
  port: "8080"
  read_timeout: 10s
  write_timeout: 10s
  max_header_bytes: 1

db:
  name: "postgres"
  host: "localhost"
  port: "5436"
  user: "postgres"
  sslmode: "disable"
  driver_name: "postgres"

auth:
  access_token_ttl: 15m
  refresh_token_ttl: 43200m #30 days
