http:
  port: "8080"
  read_timeout: 10s
  write_timeout: 10s
  max_header_bytes: 1

db:
  name: "postgres"
  host: "db"
  port: "5432"
  user: "postgres"
  sslmode: "disable"
  driver_name: "postgres"

storage:
  endpoint: "fra1.digitaloceanspaces.com"
  region: "eu-central-1"
  name: "network-storage"

auth:
  access_token_ttl: 900s #15 minutes
  refresh_token_ttl: 2592000s #30 days
